#3050488 - Support ECP/ACH transaction
shabananavas/php-bluesnap-sdk pull request #3
Opened 2019-04-29 13:17 UTC by safalliajoseph

* Add support for Alternate Transaction API (ACH/ECP)
* Updated the API version to use to be 3.0 as multiple ACH for vaulted shopper is supported only in API version 3. Will have to check hosted payment fields payment

2019-04-29 13:17 UTC, safalliajoseph commented
Hey @krystalcode - Could you please review. Thanks!

2019-04-29 13:55 UTC, shabananavas commented on src/Bluesnap/Api.php
> +            'bluesnap-version' => '3.0',
Does the 3.0 version work for all the other transaction calls as well? I'm thinking we shouldn't hard-code this and make it so that it is configurable as this might have issues with other API calls?

2019-04-29 13:57 UTC, shabananavas commented on src/Bluesnap/Adapter.php
> -
Is this change really necessary? Isn't the separation good to keep the request call separate from the code?

2019-05-01 23:19 UTC, krystalcode requested changes

2019-05-01 23:19 UTC, krystalcode commented on src/Bluesnap/Api.php
> +            'bluesnap-version' => '3.0',
@safalliajoseph Was the code without this addition working for you? We should keep the changes to this SDK to as minimal as possible as it's not well written/architected. The long-term goal should be to write a better SDK.

2019-05-01 23:19 UTC, krystalcode commented on src/Bluesnap/Adapter.php
> -
Agreed, original code looks good. Should group relevant code together and separate from other code with empty lines.

2019-05-07 09:12 UTC, safalliajoseph commented on src/Bluesnap/Api.php
> +            'bluesnap-version' => '3.0',
https://developers.bluesnap.com/docs/authentication
In here you can see `Version 3.0: Functionality was added to support Multiple ACH accounts for vaulted shoppers.` 
When the version was not 3.0, I was not able to add multiple ACH for vaulted shopper

2019-05-07 09:21 UTC, safalliajoseph commented on src/Bluesnap/Adapter.php
> -
Reverted back

2019-05-13 09:05 UTC, safalliajoseph commented on src/Bluesnap/Api.php
> +            'bluesnap-version' => '3.0',
@krystalcode I had asked bluesnap whether all transaction type would work with Version 3 and they said 

> `Yes, our API version 3.0 has backward compatibility to all our API resources, so you can use version 3.0 on all your API calls.`

So it seems like it is safe to use version 3.0 in all API calls

2019-05-21 04:17 UTC, merged